'''
Author: Carson Woods
1/25/2018

By submitting the generated README you are assuming responsibility for the contents of the file.
Please check everything before submitting because it is possible for an error could be created unintentionally.
'''

import os
from os import listdir
from os.path import isfile, join
from sys import platform

def GenerateReadme():
    '''
    GenerateReadme(): Generates a README.txt to save time when submitting homework.
    Does not generate file descriptions, but will autofill file names, directory name.
    Sorts files alphabetically in the archive list and places '.py' files before '.txt' files

    Uses Python's OS funcationality to get file directories, file names, and writing files
    '''
    try:
        dirpath = os.getcwd()

        files = [f for f in listdir(".") if isfile(join(".", f))]

        f = open("README.txt","w+")

        if platform == "linux" or platform == "linux2":
            # linux
            parentFile = dirpath[dirpath.rfind("/")+1:]
        elif platform == "darwin":
            # OS X
            parentFile = dirpath[dirpath.rfind("/")+1:]
        elif platform == "win32":
            # Windows...
            parentFile = dirpath[dirpath.rfind("\\")+1:]




        f.write("README for " + parentFile + "\n\n")
        f.write("\tArchive of " + parentFile + ".zip\n")
        files.sort()

        #Generates Archive Contents List, excludes .DS_Store File
        for x in files:
            if (x != ".DS_Store") and (x != "MakeReadme.py"):
                if x[len(x)-3:] == ".py":
                    f.write("\t\t" + "--" + str(x) + "\n")

        for x in files:
            if x != ".DS_Store" and (x != "MakeReadme.py"):
                if x[len(x)-4:] == ".txt":
                    f.write("\t\t" + "--" + str(x) + "\n")


        f.write("\n\tDescriptions of Programs functionality\n")

        for x in files:
            if x != ".DS_Store" and (x != "MakeReadme.py"):
                if x[len(x)-3:] == ".py":
                    f.write("\t\t" + "--" + str(x) + ": \n\n")

        for x in files:
            if x != ".DS_Store" and (x != "MakeReadme.py"):
                if x[len(x)-4:] == ".txt":
                    f.write("\t\t" + "--" + str(x) + ": \n\n")

        print("README.txt generated at '" + dirpath + "'\nRemember to remove this script before zipping and submitting your archive.")
        print("This is a tool to help save time, but please double check everything generated by this script before submitting.")

    except:
        print("Could not generate README.txt")

def main():
    '''
    main(): Drives GenerateReadme() function.
    '''
    GenerateReadme();

if __name__ == "__main__":
    main()
